apiVersion: apps/v1
kind: Deployment
metadata:
  name: aidebugops-jenkins
spec:
  selector:
    matchLabels:
      app: aidebugops-jenkins
  template:
    metadata:
      labels:
        app: aidebugops-jenkins
    spec:
      securityContext:
          fsGroup: 1000 
          runAsUser: 0
      volumes:
        - name: aidebugops-pvc
          persistentVolumeClaim:
            claimName: aidebugops-pvc
      containers:
      - name: aidebugops-jenkins
        image: registry.digitalocean.com/docr-dailybhajans-registry/aidebugops-jenkins
        imagePullPolicy: Always
        #resources:
        #  limits:
        #    memory: "256Mi"
        #    cpu: "500m"
        ports:
        - name: http-port
          containerPort: 8080
        - name: jnlp-port
          containerPort: 50000
        volumeMounts:
          - name: "aidebugops-pvc" # name of volume
            mountPath: "/var/jenkins_home"
        
        

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aidebugops-backend
spec:
  selector:
    matchLabels:
      app: aidebugops-backend 
  template:
    metadata:
      labels:
        app: aidebugops-backend 
    spec:
      containers:
      - name: aidebugops-backend
        image: registry.digitalocean.com/docr-dailybhajans-registry/aidebugops-backend
        imagePullPolicy: Always
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aidebugops-chatbot
spec:
  selector:
    matchLabels:
      app: aidebugops-chatbot
  template:
    metadata:
      labels:
        app: aidebugops-chatbot
    spec:
      containers:
      - name: aidebugops-chatbot
        image: registry.digitalocean.com/docr-dailybhajans-registry/aidebugops-chatbot
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
