apiVersion: v1
kind: Service
metadata:
  name: aidebugops-backend-service
spec:
  selector:
    app: aidebugops-backend
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31000

---
apiVersion: v1
kind: Service
metadata:
  name: aidebugops-jenkins-service
spec:
  selector:
    app: aidebugops-jenkins
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31001

---
apiVersion: v1
kind: Service
metadata:
  name: aidebugops-chatbot
spec:
  selector:
    app: aidebugops-chatbot
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31002
---
apiVersion: v1
kind: Service
metadata:
  name: aidebugops-lb
spec:
  type: LoadBalancer
  selector:
    app: aidebugops-lb
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80