apiVersion: v1
kind: Service
metadata:
  name: aidebugops-backend-service
spec:
  selector:
    app: aidebugops-backend
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31000

---
apiVersion: v1
kind: Service
metadata:
  name: aidebugops-jenkins-service
spec:
  selector:
    app: aidebugops-jenkins
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31001
