---
# tasks file for fetch-logs

- name: Run logs
  shell: "ls -l {{ src_logs_dir }}/*.log"
  register: output

- name: Get all log files
  find:
    paths: "{{ src_logs_dir }}"
    patterns: "*.log"
    recurse: no
    # use_regex: True
  register: found_tar_files

- name: Get the logs
  fetch:
    src: "{{ item.path }}"
    dest: "{{ dest_logs_dir }}/{{ item.path | basename}}"
    flat: yes
  become: yes
  loop: "{{ found_tar_files.files }}"

- name: Compress files
  shell: "tar cvf {{ dest_logs_dir }}/logs.tar {{ dest_logs_dir }}/*.log"

#- name: Compress files
#  archive:
#    path: "{{ dest_logs_dir }}"
#    dest: "{{ dest_logs_dir }}.zip"
#    force_archive: True
#    format: zip
- name: Copy to workspace
  shell: "cp {{ dest_logs_dir }}/logs.tar {{ src_logs_dir }}/workspace/fetch-logs"
#- name: Delete files
#  shell: "rm -rf '{{ item.path }}'"
#  loop: "{{ found_tar_files.files }}"